### ISSUE TITLE
Excel 导出二进制文件，怎么做？

### ISSUE THREAD

**Issue by uiosun** [TippingGame/F8ExcelTool#1]
非游戏行业，想试试咱们这个插件，但看注释有点迷茫。

遂请教一下：

1. Excel 导出二进制文件，是什么意思？
2. 运行时直接读取 Excel 文件，支持读取公式吗？

**Comment by TippingGame** [comment]
1.可以看代码这里， IFormatter f = new BinaryFormatter();
            Stream s = new FileStream(BinDataPath + "/" + container.GetType().Name + ".bytes", FileMode.OpenOrCreate,
                FileAccess.Write, FileShare.Write);
            f.Serialize(s, container);
            LogF8.LogConfig("已序列化 " + BinDataPath + "/<color=#FFFF00>" + container.GetType().Name + ".bytes</color>");

**Comment by TippingGame** [comment]
2. 测试了简单的加法是支持的，具体实现  IExcelDataReader excelReader = null;  datas[j] = excelReader.GetString(j);

**Comment by uiosun** [comment]
> 2. 测试了简单的加法是支持的，具体实现 IExcelDataReader excelReader = null; datas[j] = excelReader.GetString(j);

收到，我测了常用的 ROUND、INDEX、跨表公式，全部支持，太好用了！
